### ISSUE TITLE
crash on startup

### ISSUE THREAD

**Issue by freopt** [Asek3/Radium#11]
https://www.toptal.com/developers/hastebin/hacegivofe.css

**Comment by freopt** [comment]
https://www.curseforge.com/minecraft/mc-mods/ninjaphenixs-container-library
https://www.curseforge.com/minecraft/mc-mods/expanded-storage-forge

incomapatbile with these

**Comment by Asek3** [comment]
Is your client can run without radium?

**Comment by freopt** [comment]
apparently not
