### ISSUE TITLE
Violation of GNU Lesser General Public License v3.0

### ISSUE THREAD

**Issue by 2No2Name** [Asek3/Radium#18]
The content of this repository contains content from https://github.com/CaffeineMC/lithium-fabric without complying with the license at https://github.com/CaffeineMC/lithium-fabric/blob/1.18.x/dev/LICENSE.txt .
@Asek3 

Please state clearly the where the code is taken from and which modifications were made.

**Comment by Asek3** [comment]
okaaaay, there is solution
