### ISSUE TITLE
Villager not restocking

### ISSUE THREAD

**Issue by Atlantispy** [Asek3/Radium#5]
Hi, unsure 100% if it's lithium, but the villagers appear to not be restocking trades overnight. This mod seems most likely to be the one causing it.

**Comment by Asek3** [comment]
> Hi, unsure 100% if it's lithium, but the villagers appear to not be restocking trades overnight. This mod seems most likely to be the one causing it.

Can you send modlist?

**Comment by Atlantispy** [comment]
Sure, ones I had installed were:

- 3D skin layers
- AI Improvements
- Alexsmobs
- AmbientSounds
- Architectury
- Citadel
- Cleancut
- Clumps
- Create
- CreativeCore
- Croptopia
- Dynview
- Enhanced Visuals
- EntityCulling
- Ferritecore
- Krypton
- LazyDFU
- Placebo
- Radium
- Terralith

This was my list when the bug happened, it has since changed, but the trades haven't restocked.

**Comment by Asek3** [comment]
Try to set
mixin.alloc.chunk_ticking=false
mixin.alloc.chunk_random=false
in config.

**Comment by Atlantispy** [comment]
That seems to have fixed it. All my trades are open again :)
