### ISSUE TITLE
[1.18.1] Vanilla shader parity still an issue in latest update.

### ISSUE THREAD

**Issue by KKotik** [Asek3/Radium#7]
Issue #4 still happen, but now it is rotated from right to left. https://user-images.githubusercontent.com/45950781/151565203-c87245bf-6a66-4ba7-8fad-24f3c35b2149.png
I suggest you to send dev versions to test changes in my case, so I can help more.

**Comment by Asek3** [comment]
Oh shit, seems to be not resolved

**Comment by KKotik** [comment]
Tested, seems like working fine for me with latest update.
