### ISSUE TITLE
Mod to take inspiration from?

### ISSUE THREAD

**Issue by Atlantispy** [Asek3/Radium#8]
Hi, was just browsing other mods and found this:

https://www.curseforge.com/minecraft/mc-mods/does-it-tick

Boasting performance improvements that I assume are similar to Lithium (although for 1.16).

Are there any additional changes this makes that you could take inspiration from?

**Comment by Asek3** [comment]
I don't think it's Radium style, I mean Radium tries not to affect vanilla mechanics

**Comment by Atlantispy** [comment]
Well if you ever make a Does It Tick reforged hit me up for that lol

**Comment by Asek3** [comment]
Maybe in future
